// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// load_bcidat
Rcpp::List load_bcidat(std::string file, bool raw = false);
RcppExport SEXP bcidat_load_bcidat(SEXP fileSEXP, SEXP rawSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type file(fileSEXP );
        Rcpp::traits::input_parameter< bool >::type raw(rawSEXP );
        Rcpp::List __result = load_bcidat(file, raw);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
