# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_bcidat <- function(file, raw = FALSE) {
    .Call('_bcidat_load_bcidat', PACKAGE = 'bcidat', file, raw)
}

